# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NuskinVN CRM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NuskinVN CRM
  pod 'Alamofire'
  pod 'CorePlot'
  pod 'SQLite.swift'

  target 'NuskinVN CRMTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
