# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NuskinVN CRM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NuskinVN CRM
  pod 'Alamofire', '= 4.5.1'
  pod 'Charts', '= 3.0.2'
  pod 'SQLite.swift', '= 0.11.3'
  pod 'Localize-Swift', '= 2.0'
  pod 'Reachability'
  pod 'FontAwesomeKit', '= 2.2.1'
  pod 'Daysquare', :git => 'https://github.com/unixzii/Daysquare.git'
  pod 'RxSwift',    '= 3.0'
  pod 'RxCocoa',    '= 3.0'

  target 'NuskinVN CRMTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
